# Generated by Django 3.0.3 on 2020-04-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusersettings',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_telegram.TelegramUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_telegram.TelegramUser'),
        ),
    ]
